# Building Blocks {#chap-blocks}

This chapter contains concepts, definitions, and mathematical techniques that will
be used throughout the semester. Critical terms to understand are given in **bold**.

## Planning for Human Systems

If you look out on any sufficiently busy road, you will see a steady stream of
vehicles passing by. Each vehicle is largely indistinguishable from the others,
and it is easy as an engineer responsible for that road to see the cars driving
by as little more than an input to a problem. But the *people* inside the cars
should not be indistinguishable from each other. Each person who is driving or
riding in each of those cars has their own reasons to be driving on that road.
One person might be driving to work; one person might be trying to get home to
his or her family. Another car might hold a family going on vacation, or a group
of friends heading to a movie.

If you don't recognize that each person who travels is different, with different
needs and purposes, then it is easy to look only at the **supply** of transportation
infrastructure. Is the road wide enough? Is the traffic signal timed appropriately?
But as with anything in the economy transportation is a function of both supply 
and **demand**. Why are so many people trying to get down this one road *right now*?
Why didn't more people take transit? Why didn't some people choose a different
destination? Or why didn't some people just stay home in the first place? 

Transportation planning therefore must be concerned with both the supply of
infrastructure and the demand for travel. For the most part, economists consider
travel a **derived demand**, which means people only go to the hassle of 
travelling somewhere if they have some other reason to be there. No one 
typically just drives around (with the possible exception of teenagers on a
weekend night); they are going to work, or school, or a social engagement, or
*something*.

Travel demand has not been stable over time. The availability of inexpensive
automobiles in the 20th Century created demand for inter-city and intra-urban
roads that did not exist before. Rising labor force participation rates for
women radically changed the number and types of trips the average household
makes in an average day. Technological developments like teleconferencing and
smartphone-enabled ridehailing could generate different trends. At the same
time, populations in most regions continue to grow. **Planning** for future 
transportation infrastructure is difficult because of the uncertainty of the
future, but it is necessary to keep economies rolling and preseve or improve
quality of life.

In the United States and most societies with some democratic process,
**decisions** about what transportation facilities to build, which policies to
implement, and how to build a city generally fall to **decision makers**. These
decision makers consist of mayors, city councils, planning commissions, 
state legislatures, Congress, state and federal agencies, and innumerable others
who are elected by the public, or who are accountable to others who have been.
In making decisions about how to spend public money on civil infrastructure or
enact tax or other policies, decision makers consult **plans** developed by
professional engineers and planners.

As engineers and planners, we are rarely in a position to *make* decisions, but
we have a responsibility to provide accurate data and technical analysis to 
support decision makers. There is a misconception that transportation planners
must accurately predict the future to be relevant. The purpose of transportation
planning is not to perfectly envision what will happen under every scenario, 
it is to provide information that will help make good decisions now so that
the future is at least as pleasant as the present. We all have hopes for what
our lives and community will look like ten or twenty years from now; it may not
be possible for anyone to provide analysis entirely free of all personal bias.
But as you conduct your work as an engineer and planner, you owe the public your
integrity and competence as you provide information to their representatives.


## Travel Model Building Blocks

### Data Collection and Terms

### Travel Analysis Zones

SE Data


### Highway Networks

Functional Type

Link capacity

Free-flow speed

Centroid connectors

### Matrices

Skim matrices

OD matrices


## Statistical and Mathematical Techniques

Many elements of travel modeling and forecasting require complex numerical and
quantitative techniques. In this section we will present some of these techniques.

### Iterative Proportional Fitting

### Regression Analysis

### Numerical Optimization

## Homework {-#hw-blocks}

> Some of these questions require a completed run of the demonstration model.
For instructions on accessing and running the model, see the [Appendix](#app-demomodel)

1. How does recreational transportation --- i.e., going for a bike ride --- fit into the
theory of derived demand for travel?

1. Think about a recent transportation-related construction project you have
seen in your community. Find an article in a local newspaper discussing the project.
Why was the project built (or why is it being built)? Who supports the project?
Does anyone oppose the project? Write a short paragraph including a link and 
citation to the article.

1. Download the [rmove](https://rmove.rsginc.com/) mobile application, and log 
in with the password given you by the instructor. Track your daily activies and
trips for *three days*. You may include at most one weekend day. Write a short
summary of your activities, including:

    - How many trips you took each day
    - The mode split of all your trips

1. With the TAZ layer and socioeconomic data in the demonstration model, make a
set of choropleth maps showing: total households; household density; total jobs;
job density; density of manufacturing vs office vs retail employment. Compare
your maps with aerial imagery from Google Maps or OpenStreetMap. Describe the
spatial patterns of the socioeconomic data in the model region. Identify which
zones constitute the central business district, and identify any outlying
employment centers.

1. With the highway network layer in the demonstration model, create maps
showing: link functional type; link free flow speed; and link hourly capacity.
Compare your maps with aerial imagery from Google Maps or OpenStreetMap.
Identify the major freeways and principal arterials in the model region. *Note*:
you will need to run the demonstration model through the network setup step to
calculate the capacities and append them to the link.
   
1. Find the shortest free-flow speed path along the network between two zones.
Find the shortest distance path between the same two zones. Are the paths the
same? Do the paths match what an online mapping service shows for a trip in the
middle of the night?

1. Open the highway assignment report, which shows vehicle hours and miles
traveled by facility type. What percent of the region's VMT occurs on freeways?
What percent of the region's lane-miles are freeways? 

1. Open the output highway network. Create a map of the 
highway links showing PM period level of service based on the volume to capacity
ratios in the table below. How would you characterize traffic in Roanoke? Which
is the worst-performing major facility?


