project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: Urban Transportation Planning
  author:
    - name: Gregory Macfarlane, PhD, PE
      email: example@example.com
  editor:
    - name: Hayden Atchley
      email: atchley.sha@protonmail.com
  description: |
    These are notes and assignments related to the _Urban Transportation Planning_ class at BYU.
  date: today
  date-format: MMMM D, YYYY
  cover-image: /images/cover.jpg
  # downloads: [pdf, epub]
  sidebar:
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - tripgen.qmd
    - distribution.qmd
    # - mode_choice.qmd
    # - assignment.qmd
    # - process.qmd
    - references.qmd
  # appendices:
  #   - demo_model.qmd
  #   - rstudio.qmd

execute:
  warning: false
  echo: false
  cache: false
  freeze: auto

# reference-location: margin
# citation-location: margin
bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: true
    toc: true
    lof: true
    lot: true
    titlepage: vline
    # titlepage-bg-image: "img/corner-bg.png"
    titlepage-logo: "img/logo.png"
    titlepage-theme:
      vrule-text: "Hello, world!"
    # titlepage-header: "The Publisher"
    # template: eisvogel.latex
    # titlepage: true
    # book: true
    # titlepage-background: bg/background4.pdf
    # float-placement-figure: htbp
    # number-depth: 1
    # toc-depth: 2
    # documentclass: scrreport
  # epub:
  #   cover-image: /images/cover.jpg
